version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.9.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - es7_12net
 # kibana Docker 环境变量： https://www.elastic.co/guide/cn/kibana/current/docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana7_12
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - XPACK_SECURITY_ENCRYPTIONKEY=encryptionKeysecurity1234567890abcdefghijklmn
      - XPACK_REPORTING_ENCRYPTIONKEY=encryptionKeysecurity1234567890abcdefghijklmn
    ports:
      - "5601:5601"
    networks:
      - es7_12net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es7_12_01
    environment:
      - cluster.name=geektime
      - node.name=es7_12_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_12_01,es7_12_02
      - cluster.initial_master_nodes=es7_12_01,es7_12_02
    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - /d/es/node1/data:/usr/share/elasticsearch/data
      - /d/es/node1/logs:/usr/share/elasticsearch/logs
      - /d/es/node1/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    networks:
      - es7_12net
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es7_12_02
    environment:
      - cluster.name=geektime
      - node.name=es7_12_02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_12_01,es7_12_02
      - cluster.initial_master_nodes=es7_12_01,es7_12_02
    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - /d/es/node2/data:/usr/share/elasticsearch/data
      - /d/es/node2/logs:/usr/share/elasticsearch/logs
      - /d/es/node2/plugins:/usr/share/elasticsearch/plugins
    networks:
      - es7_12net

#volumes:
#  es7data1:
#    driver: local
#  es7data2:
#    driver: local

networks:
  es7_12net:
    driver: bridge
